module.exports=function(grunt){
    grunt.initConfig({
        pkg:grunt.file.readJSON('./package.json'),
        sass:{
            dist:{
                options:{
                    style:'compressed',
                    sourcemap:'none'
                },
                files:{
                    'www/css/indexStyle.css':'www/css/sass/index-style.scss',
                    'www/css/contentStyle.css':'www/css/sass/content-page-style.scss'
                }
            }
        },
        uglify:{
            options:{
                banner:'/*Created by Nuno Machado*/\n'
            },
            build:{
                files:{
                    'www/src/build/main.min.js':[
                        'www/src/Alerts.js',
                        'www/src/PopupBar.js',
                        'www/src/Main.js'
                    ]
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.registerTask('default',['sass','uglify']);
};